on: push
jobs:
  enviroment:
    runs-on: ubuntu-latest
    steps:
      - name: use now repository
        uses: actions/checkout@v4
      - name: Installing Buiding enviroment
        run: |
          ls
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
      - name: show me user
        run: whois
      - name: configurate build device setting
        run: |
          cp -f defconfig/mt7981-ax3000.config .config
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: building
        run: |-
          chmod -R 755 ./
          make V=s -j$(nproc)
